# Generated by Django 2.2.16 on 2020-11-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapi', '0002_auto_20201031_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(max_length=13),
        ),
    ]
