# Generated by Django 2.2.16 on 2020-10-12 14:57

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapi', '0002_auto_20201009_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
