# Generated by Django 2.2.16 on 2020-12-05 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmediaapi', '0004_commentrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.BooleanField(null=True)),
                ('favourite_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('favourite_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='socialmediaapi.Post')),
            ],
        ),
    ]
